### ISSUE TITLE
[Feature Request] Select box and select-all option for files

### ISSUE THREAD

**Issue by Joly0** [bewcloud/bewcloud#10]
Hey, it would be great, to have small checkboxes next to files and an option to select-all files, so i could easily move or delete multiple files at once

**Comment by BrunoBernardino** [comment]
Oh, that's a nice idea. I usually do bulk operations on synchronised directories, so I haven't missed this yet.

**Comment by BrunoBernardino** [comment]
This is how it's looking in the latest release:

<img width="476" alt="Screenshot 2024-09-02 at 16 11 14" src="https://github.com/user-attachments/assets/2e005767-c4ed-43ec-981c-2f75c39b8af0">

<img width="518" alt="Screenshot 2024-09-02 at 16 11 24" src="https://github.com/user-attachments/assets/5ddfa49b-8806-4b01-895b-ab526de5be20">

<img width="539" alt="Screenshot 2024-09-02 at 16 11 29" src="https://github.com/user-attachments/assets/ddfddb78-ad1f-42e0-94b3-7023abe40cb7">

**Comment by Joly0** [comment]
Very cool, thanks for implementing this
