### ISSUE TITLE
[Bug] Disabling dashboard doesnt disable dashboard

### ISSUE THREAD

**Issue by Joly0** [bewcloud/bewcloud#11]
Hey, because i currently only need the files feature, i disabled all options in the .env file and only left this option in:
`CONFIG_ENABLED_APPS="files"`
but nontheless i still see this:
![grafik](https://github.com/bewcloud/bewcloud/assets/13993216/2ebf8ed1-c561-4bd5-a5f9-1460afc73434)
Is this intended?

**Comment by BrunoBernardino** [comment]
Hey @Joly0 indeed the `dashboard` and the `files` can't be disabled as explained in https://github.com/bewcloud/bewcloud/blob/main/.env.sample#L17 because it would require a lot of changes in the code to check if those exist or not, and they don't use resources if they're not used.
