### ISSUE TITLE
Can't login after signing up

### ISSUE THREAD

**Issue by AndyDroid10X** [bewcloud/bewcloud#15]
Good afternoon!
I have successfully deployed it via Docker and Dockage. 
But after signing up, I can't log in to my account. Instead, it redirects me to the login page infinitely.

bew-website-1     | 2024-10-28T09:42:42.124Z - [303] GET http://bew.ntares.uz/
bew-website-1     | 2024-10-28T09:42:42.342Z - [200] GET http://bew.ntares.uz/login
bew-website-1     | 2024-10-28T09:42:54.809Z - [303] POST http://bew.ntares.uz/login
bew-website-1     | 2024-10-28T09:42:55.243Z - [303] GET http://bew.ntares.uz/
bew-website-1     | 2024-10-28T09:42:55.669Z - [200] GET http://bew.ntares.uz/login

Backed by Caddy reverse proxy

**Comment by BrunoBernardino** [comment]
Hi @AndyDroid10X looks like the session cookie isn't being properly set. What's your `.env` file like? Also, note that a non-localhost server running expects SSL enabled.

Here's the relevant code, if you want to take a look or change something too:

https://github.com/bewcloud/bewcloud/blob/560ea569a0dee3db26e46b365d0d371f090bc467/lib/auth.ts#L152-L161
