### ISSUE TITLE
How to add users?

### ISSUE THREAD

**Issue by AndyDroid10X** [bewcloud/bewcloud#16]
Can I add some users without allowing signups? I don't see any option in the settings.

**Comment by BrunoBernardino** [comment]
Unfortunately, no. The idea would be to allow signups, create the users you want via signup, then disable it. I'd be happy to consider building some simple user CRUD admin interface if enough people ask for it, though.

**Comment by AndyDroid10X** [comment]
Thank you a lot for your help!
