### ISSUE TITLE
Migration process returns 0 even if it fails

### ISSUE THREAD

**Issue by Kaurin** [bewcloud/bewcloud#18]
This is more of a deno issue I think, but it's super anti-pattern for containerization.

Init  containers need to be able to fail on actual job failure so Kubernetes can reschedule them and retry. This saves the user from writing unnecessary health-checks in vast majority of cases.

I have worked around this by delaying execution of deno for my particular problem (parallel spin-up of DB and app), however in the future other migration errors might pop up and go unnoticed regardless of my workaround.

It would be best if the migration can somehow fail if it is not successful.

Repro: Bring down the database and run

```bash
deno run --allow-all /app/migrate-db.ts
echo $?
```

**Comment by BrunoBernardino** [comment]
Ah, good point. We should exit the process with a `-1` or something like that if it can't connect to the database. Feel free to propose a PR!
