### ISSUE TITLE
Question: TLS and in-transit

### ISSUE THREAD

**Issue by dawidmachon** [bewcloud/bewcloud#20]
Question, data during sync on open network is encrypted in any way?

**Comment by BrunoBernardino** [comment]
@dawidmachon it'll be up to your proxy to enable TLS, it's not done by the container. I recommend [caddy](https://caddyserver.com) because it has easy built-in TLS via Let's Encrypt. Here's an example entry for a `Caddyfile`:

```Caddyfile
cloud.example.com {
	tls you@example.com
	encode gzip zstd

	reverse_proxy localhost:8000 {
		header_up Host {host}
		header_up X-Real-IP {remote}
		header_up X-Forwarded-Host {upstream_hostport}
	}
}
```
