### ISSUE TITLE
Activation of the email address is not possible.

### ISSUE THREAD

**Issue by MalteKiefer** [bewcloud/bewcloud#23]
Hello,

I have set up Bewcloud on my system, but I'm unable to proceed beyond the registration process. My email addresses are not receiving any confirmation codes:

Google (gmail.com)
Tutanota (tutanota.com)
Do I need to specify a mail server in the .env file?

**Comment by BrunoBernardino** [comment]
Hi @MalteKiefer have you setup emails in the `.env` file? (`CONFIG_ENABLE_EMAILS="false"` means no emails are sent, thus confirmation codes show in the server logs instead)

Additionally, you might want to check https://github.com/bewcloud/bewcloud/issues/15 for some other considerations (like the `BASE_URL`) for logging in.

**Comment by MalteKiefer** [comment]
Thanks for the response.
In the logs, I see only this:

![image](https://github.com/user-attachments/assets/05309b7a-fb18-40fa-9954-f4871aedd120)

**Comment by BrunoBernardino** [comment]
Thanks @MalteKiefer and what's in your `.env` file?

FYI You might want to remove/redact that image because it exposes your hostname.

**Comment by BrunoBernardino** [comment]
Ok, all seems well and I _think_ the signup worked, but login isn't creating the cookie in the right place.

I thought you were initially talking about the code not working for signup, but it's just not asked, and nothing shows in the logs, I was thinking of an earlier version.

I saw in the logs a host, but your `BASE_URL` points to `http://localhost:8000`. This was the same issue in #15 where those need to match for the session cookie to be properly set and it _expects_ SSL. If that's not available, and you can't use `localhost` to access, then you need to make some changes in the code to disable it. It's explained in #15 as well.

Note: remove/change the password in the `docker-compose.yml` file you've shared, as it's visible here.

**Comment by MalteKiefer** [comment]
No matter what I do, it's not working. I even set up a Brevo account and entered the Brevo API key, but I’m still not receiving any emails. I don’t know what else to do.

**Comment by BrunoBernardino** [comment]
@MalteKiefer there is no email to receive. A verification code is only asked when you're signing up, _if_ emails are set to be sent. Given what you shared above, they aren't necessary.

You have signed up, correct? What's wrong is the `BASE_URL` because that makes the session cookie not being set properly.

Do you understand what the problem is? And if so, do you understand the options to fix it? I've shared that above and in the linked issue.

**Comment by MalteKiefer** [comment]
Alright, I think we're talking past each other.
Here are the steps I completed following your feedback.

1. Adjusted the .env file based on your recommendations.
2. Stopped and deleted the containers.
3. Deleted all volumes and local files.
4. Pulled the latest version and restarted the container.
5. Configured the Brevor token and activated email notifications.
6. Restarted the container.
7. Registered a new account.
8. Received a message indicating an email with the token was sent.
9. Did not receive the token.
10. Registered again with a different email address.
11. Encountered the same issue.

**Comment by BrunoBernardino** [comment]
Thanks! Let's not activate the emails yet as that's just adding a variable to something that wasn't working before (login) and which unnecessarily makes it harder to debug what's wrong. Setting `CONFIG_ENABLE_EMAILS="false"` is enough and you don't need to change the `BREVO_API_KEY`.

On point 1, I imagine you're saying you changed the `BASE_URL` to something like `BASE_URL="https://example.com"`, where `https://example.com` is what you type in your browser to access bewCloud. Is that correct?

If so, is that an SSL/HTTPS host? If so and if there's no error in the logs, can you check in your browser's storage for what cookies exist for that domain?

**Comment by MalteKiefer** [comment]
1. Yes that is correct
2. Yes it is an SSL host with Caddy as webserver
3. I sign up again, see the message on the screenshot. No Cookie, nothing in the session or local storage
![image](https://github.com/user-attachments/assets/ac817019-bb84-4619-85e0-cae58c0b12ef)

**Comment by BrunoBernardino** [comment]
And if you try to login? The notification title might be a bug.

**Comment by MalteKiefer** [comment]
LOL :facepalm: 
It works

**Comment by BrunoBernardino** [comment]
For that new issue you should have something in the server logs.

**Comment by BrunoBernardino** [comment]
Check if it's https://github.com/bewcloud/bewcloud/issues/19 though you did have those set above.

**Comment by MalteKiefer** [comment]
Fixed it.
Missing permission.
Thanks for the help.

**Comment by BrunoBernardino** [comment]
@MalteKiefer I've tweaked the success notification title in v1.4.5 to avoid confusion in the future.
