### ISSUE TITLE
Can not run on arm device?

### ISSUE THREAD

**Issue by muava12** [bewcloud/bewcloud#24]
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/59fda46a-686f-4560-8353-97c1471399bc">

Is bewcloud support arm device?

**Comment by BrunoBernardino** [comment]
[Deno supports arm](https://github.com/denoland/deno/releases), but the [denoland docker image](https://hub.docker.com/r/denoland/deno) might not. I'm happy to accept a PR that also builds those, if that's possible.
