### ISSUE TITLE
Stay blocked on the login page 

### ISSUE THREAD

**Issue by Raphencoder** [bewcloud/bewcloud#26]
Hi !

Thanks for this cool project !
I wanted to make it run using docker compose, I enter my email and password, I got a message saying it was register, but when I enter my cred on the login page and hit login, I just have the login page again. I checked the closed issues about it, and I edit the base_url with the ip adress + port.
Yet, I still have a message in log
`Local: http://localhost:8001/`
The port is okay since I changed it to 8001, but the IP adress should be another.
When I check the BASE_URL variable inside the container, I have the good ip address, I tried to kill and re-run again, same results.
In the log I got a 303 error
2024-12-04T16:00:25.140Z - [303] GET http://IP-ADDRESS:8001/
Any ideas ?

**Comment by BrunoBernardino** [comment]
Hi @Raphencoder please. check https://github.com/bewcloud/bewcloud/issues/23 and https://github.com/bewcloud/bewcloud/issues/15 for similar issues. Generally it's the `BASE_URL` that's not correct or not using SSL, and that's expected.

**Comment by Raphencoder** [comment]
Thanks for the quick reply.
I review them, from what you said it cannot works without SSL ?

**Comment by BrunoBernardino** [comment]
The code won't work if you use an IP, IIRC. If you can't put a caddy proxy in front of it, you can tweak the code to allow what you want and reduce its security. I've explained where that can be changed in #15.

**Comment by Raphencoder** [comment]
Would you approve an MR of an env variable of our local ip adress in order to avoid replace manually in the code or to put a proxy ?

**Comment by BrunoBernardino** [comment]
Since that greatly reduces the security, I would not, I'm afraid. You're welcome to create a fork and link it here, so people can see they have an option for it.

**Comment by BrunoBernardino** [comment]
BTW, there's already an option to accept an IP address for the cookie, but it needs to have SSL: https://github.com/bewcloud/bewcloud/blob/bbf8683004a2ee7f3253707bf191130473e2bdcb/lib/auth.ts#L163-L167

So what I'm not comfortable accepting is not requiring SSL (`secure: true` in the session cookie), when not accessing via `http://localhost`, just to be clear.

**Comment by Raphencoder** [comment]
Understand, thanks for the reply and the proposition 👍 

Another idea, can we check that the IP is in the reserved local ipv4 IP (https://en.wikipedia.org/wiki/Reserved_IP_addresses) ?
It allows to connect to your instances locally from you local network or a VPN client

Thanks again

**Comment by BrunoBernardino** [comment]
@Raphencoder I suppose I'd accept a PR of that added to the `isRunningLocally` check here:

https://github.com/bewcloud/bewcloud/blob/bbf8683004a2ee7f3253707bf191130473e2bdcb/lib/auth.ts#L158
