### ISSUE TITLE
Docker compose : invalid yaml

### ISSUE THREAD

**Issue by bohwaz** [bewcloud/bewcloud#31]
Trying "docker compose up" returns an error message:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.website.env_file contains {"path": ".env", "required": true}, which is an invalid type, it should be a string
```

**Comment by Bigceru** [comment]
Can you please post your `docker-compose.yml` file?

**Comment by bohwaz** [comment]
It's the one provided with this repo, I didn't change one byte inside.

**Comment by Bigceru** [comment]
Try editing `docker-compose.yml` as follow:
- Before
```
 env_file:
      - path: .env
        required: true
```
- After
```
env_file:
      - .env
```

**Comment by bohwaz** [comment]
Different error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.website.env_file contains {"path": ".env"}, which is an invalid type, it should be a string
```

Weird.

If I remove the complete 'env_file' section and sub-items, there is no error.

**Comment by bohwaz** [comment]
OK I could make it work by using:

`env_file: '.env'`

directly.

**Comment by BrunoBernardino** [comment]
Thanks for confirming you fixed it!
