### ISSUE TITLE
Error with Render

### ISSUE THREAD

**Issue by parvenall** [bewcloud/bewcloud#33]
Got this when I tried to deploy with Render. Do I need upgrade to paid Render plan?

```
A render.yaml file was found, but there was an issue.
databases[0].plan
    Legacy Postgres plans, including 'starter', are no longer supported for new databases. Update your database instance to a new plan in your render.yaml
```

**Comment by BrunoBernardino** [comment]
Thanks for reporting this! Can you try changing it from `starter` to `free` and seeing if it works? I'm looking at https://render.com/docs/blueprint-spec#database-fields for that.

**Comment by BrunoBernardino** [comment]
Seems something's wrong with the database setup. I guess they changed things a lot since the last time I tested this. Let me know if you can figure it out, otherwise I'll try to look into it next week.

**Comment by NexRX** [comment]
I just stumbled across this issue because i'm trying bewcloud for the first time (v1.4.6, self-hosted) and I too am seeing
```
No TLS options are allowed when host type is set to "socket"
```
Any clues whats going on? Also, if things are working correctly, how do i find the default login credentials?

**Comment by BrunoBernardino** [comment]
@NexRX is that on Render? There are no default login credentials, the first signup will be your login credentials.

**Comment by BrunoBernardino** [comment]
@parvenall can you please confirm it's working for you, now?
