### ISSUE TITLE
I get a constant 404 error when I use reverse-proxy

### ISSUE THREAD

**Issue by Onotot** [bewcloud/bewcloud#34]
Hello. When I use nginx as reveerse proxy I get a constant error in bewcloud logs.
`[404] GET http://antek.fyi/index.php/apps/files/preview-service-worker.js`
The server works and displays everything, but I would like to get rid of the error
The proxy settings are like this:
`location / {
           #  proxy_buffering off;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme;
           proxy_set_header Host $http_host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header Range $http_range;
           proxy_set_header If-Range $http_if_range;
           proxy_redirect off;
           proxy_pass http://bewcloud:8000; # i use hostname from docker
           }
`

Should I add something? 
I use version 1.4.3 because it doesn't have the deno error on startup.

**Comment by BrunoBernardino** [comment]
Hi @Onotot ! That URL path doesn't exist in bewCloud, so the 404 is expected. `index.php` doesn't even make sense with Deno, so I'm guessing it's something with your browser (maybe an extension, maybe some cached thing for the same domain, asking for a file that doesn't exist).
