### ISSUE TITLE
Signup without email doesn't seem to work

### ISSUE THREAD

**Issue by leckye** [bewcloud/bewcloud#9]
Hello!
I wanted to try Bewcloud. 
I used the docker-compose file provided and rename .env.sample to .env.
Everything was deployed successfully (including db migration).
I kept CONFIG_ALLOW_SIGNUPS="false" and CONFIG_ENABLE_EMAILS="false", then use signup with mail but i cannot used the credentials filled in the signup form to login. There is no invalid credentials message when i click on login, only a redirection to the login page with a resetted form.
Docker logs doesn't display any error.
Can you help me please?
cheers

**Comment by BrunoBernardino** [comment]
Hi @leckye this sounds like something with the cookies not being properly set/read. Could be related to what was seen with the reverse proxy setup in #6 as well. I'll need to see the `docker-compose.yml` or understand better how you run it and access it, in order to help.

**Comment by BrunoBernardino** [comment]
If that's what it is, if you try wrong credentials, you should see an error, though.

**Comment by BrunoBernardino** [comment]
Try changing `BASE_URL="http://localhost:8000"` in your `.env` file to the IP you use to connect.

**Comment by BrunoBernardino** [comment]
You can try `docker compose up --build` to force building with the new `.env` file.

**Comment by BrunoBernardino** [comment]
You can connect to the container and `cat` the `.env` file contents in `/app/.env` to see if it's being properly added or not.

**Comment by BrunoBernardino** [comment]
303 means the cookie was set and you're being redirected. The fact your browser isn't saving the cookie means something is wrong with the host. Can you try using `localhost` and map it to the private IP you need via `/etc/hosts`?

**Comment by BrunoBernardino** [comment]
> * users need to be able to create a symlink to create share folder right?
If by users you mean someone with access to the server/container file structure, yes.

> * it is not possible to use Bewcloud to share a folder or a file to an external user using a public link

It is not, no. All file access requires a valid authentication through cookies or basic auth (using the Dav password), and it'll give full access to everything.

**Comment by zPhoeniqz** [comment]
Hi, I'm experiencing the same problem mentioned in the original comment.

> You can try `docker compose up --build` to force building with the new `.env` file.

Tried it, didn't work

> You can connect to the container and cat the `.env` file contents in `/app/.env` to see if it's being properly added or not

_There is no `.env` file_ in `/app`, only an `.env.sample`, which is... weird. I could confirm though, that the environment variables are loaded by changing `CONFIG_ALLOW_SIGNUPS` to `"true"` and creating another account, which was successful

**Comment by zPhoeniqz** [comment]
What is added to the bewcloud logs when I click the login button with my credentials entered:
```
bewcloud-1    | 2024-11-09T12:26:13.275Z - [303] POST http://phoeniqz.port0.org/login
bewcloud-1    | 2024-11-09T12:26:13.296Z - [303] GET http://phoeniqz.port0.org/
bewcloud-1    | 2024-11-09T12:26:13.324Z - [200] GET http://phoeniqz.port0.org/login
bewcloud-1    | 2024-11-09T12:26:13.433Z - [304] GET http://phoeniqz.port0.org/styles.css
bewcloud-1    | 2024-11-09T12:26:14.289Z - [404] GET http://phoeniqz.port0.org/index.php/apps/files/preview-service-worker.js
```
